name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: '.'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean previous build
        run: rm -rf dist

      - name: Clean npm cache and lockfile (fix Rollup bug)
        run: rm -rf node_modules package-lock.json
        working-directory: ./

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./

      - name: Build site
        run: npm run build
        working-directory: ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
